[tool.ruff]
line-length = 120
extend-select = [
  "I",    # isort
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "PGH",  # pygrep-hooks
  "RUF",  # ruff
  "W",    # pycodestyle
  "YTT",  # flake8-2020
]
extend-ignore = ["B018", "B019", "PGH004"]
src = ["src"]
exclude = ["**/fixtures"]
target-version = "py37"

[tool.ruff.mccabe]
max-complexity = 10

[tool.pyright]
reportUnusedCallResult = "none"
reportUnknownMemberType = "warning"
pythonVersion = "3.9"
include = [ "build" ]
exclude = [
  # The editable hook has third party dependencies and makes bootstrapping awkward
  "build/hooks/editable_hook"
]
